export default {
  users: "users",
  payments: "payments",
  ladders: "ladders",
  players: "players",
  clubes: "clubes",
  membership: "membership",
  courts: "courts",
  translate: "translate",
  locations: "locations",
  rankings: "rankings",
  streamEvent: "streamEvent",
  matchUp: "matchUp",
  sponsors: "sponsors",
  guests: "guests",
  cameras: "cameras",
  livescore: "livescore",
  emails: "emails",
}